packages:
  - "."

overrides:
  "@redocly/openapi-core>js-yaml": 4.3.0
  "next>postcss": 8.5.22
  "next>sharp": 0.35.3

allowBuilds:
  "@parcel/watcher": false
  msw: false
  sharp: true
  unrs-resolver: false

minimumReleaseAgeExclude:
  - knip@6.29.0
