const variable = (name: string) => `var(--${name})` as const;

export const rawTheme = {
  typography: {
    fontSans:
      '"Inter Variable", "Inter", -apple-system, blinkmacsystemfont, "Segoe UI", sans-serif',
    headingLgBold: "700 3rem/3.5rem var(--font-sans)",
    headingLgBoldCompact: "700 2.25rem/2.75rem var(--font-sans)",
    headingXlRegular: "400 3.75rem/4.5rem var(--font-sans)",
    headingXlSemibold: "600 3.75rem/4.5rem var(--font-sans)",
    headingXlSemiboldCompact: "600 2.5rem/3rem var(--font-sans)",
    textXlSemibold: "600 1.25rem/2rem var(--font-sans)",
    textLgMedium: "500 1.125rem/1.5rem var(--font-sans)",
    textMdRegular: "400 1rem/1.5rem var(--font-sans)",
    textMdMedium: "500 1rem/1.5rem var(--font-sans)",
    textMdSemibold: "600 1rem/1.5rem var(--font-sans)",
    textSmRegular: "400 0.875rem/1.25rem var(--font-sans)",
    textSmMedium: "500 0.875rem/1.25rem var(--font-sans)",
    symbolMdRegular: "400 1.5rem/1.5rem var(--font-sans)",
    lineHeightTextMd: "1.5rem",
    trackingHeading: "-0.3px",
  },
  colors: {
    canvas: "#fff",
    /** Text/icons rendered on top of a saturated `primary`/`danger` fill. */
    onAccent: "#fff",
    inverseContentPrimary: "#fafafa",
    surface: "#f3f4f6",
    surfaceHover: "#e5e7eb",
    surfacePressed: "#d1d5db",
    text: "#111827",
    textSecondary: "#374151",
    textTertiary: "#4b5563",
    /**
     * De-emphasised but load-bearing: quiet icon links and the boundary of an
     * empty control. Clears the 3:1 that WCAG 1.4.11 asks of both.
     */
    textSubtle: "#6b7280",
    /** Disabled copy only. 2.5:1, which WCAG exempts for inactive controls. */
    textMuted: "#9ca3af",
    border: "#d1d5db",
    borderSubtle: "#e5e7eb",
    primary: "#4f46e5",
    primaryHover: "#4338ca",
    primaryPressed: "#3730a3",
    primarySoft: "#e0e7ff",
    primaryDisabled: "#a5b4fc",
    danger: "#e11d48",
    dangerHover: "#be123c",
    dangerPressed: "#9f1239",
    dangerSoft: "#ffe4e6",
    success: "#047857",
    successSoft: "#d1fae5",
    warning: "#b45309",
    warningSoft: "#fef3c7",
    focusRing: "rgb(55 48 163 / 24%)",
    focusRingDanger: "rgb(159 18 57 / 24%)",
    shadow: "rgb(16 24 40 / 12%)",
  },
  space: {
    1: "0.25rem",
    2: "0.5rem",
    3: "0.75rem",
    4: "1rem",
    5: "1.25rem",
    6: "1.5rem",
    8: "2rem",
    10: "2.5rem",
    12: "3rem",
    16: "4rem",
    20: "5rem",
  },
  radii: {
    xs: "0.25rem",
    sm: "0.5rem",
    md: "0.5rem",
    lg: "1rem",
    xl: "1rem",
  },
  shadows: {
    focus: "0 0 0 2px var(--color-focus-ring)",
    focusDanger: "0 0 0 2px var(--color-focus-ring-danger)",
    card: "0 18px 48px rgb(16 24 40 / 8%)",
  },
  sizes: {
    controlSm: "1.5rem",
    controlMd: "2rem",
    controlLg: "3rem",
    controlXl: "3.5rem",
    controlHeight: "var(--control-xl)",
    /** WCAG 2.5.8 minimum target size (44px) for coarse pointers. */
    tapTarget: "2.75rem",
    iconSm: "1rem",
    iconMd: "1.25rem",
    iconLg: "1.5rem",
  },
  layout: {
    pageMax: "90rem",
    pageGutterDesktop: "5rem",
    pagePaddingBlockDesktop: "3.75rem",
    contentMax: "41.125rem",
    donationLayoutGap: "5rem",
    donationMediaWidth: "37.625rem",
    donationMediaInset: "1.25rem",
    publicContentMax: "80rem",
    publicImageMax: "70rem",
    publicImageHeight: "23.5rem",
  },
  motion: {
    instant: "120ms",
    fast: "160ms",
    base: "220ms",
    celebration: "420ms",
    easeStandard: "cubic-bezier(0.2, 0, 0, 1)",
    easeEnter: "cubic-bezier(0.16, 1, 0.3, 1)",
    easePlayful: "cubic-bezier(0.34, 1.56, 0.64, 1)",
  },
} as const;

export const theme = {
  typography: {
    fontSans: variable("font-sans"),
    headingLgBold: variable("type-heading-lg-bold"),
    headingLgBoldCompact: variable("type-heading-lg-bold-compact"),
    headingXlRegular: variable("type-heading-xl-regular"),
    headingXlSemibold: variable("type-heading-xl-semibold"),
    headingXlSemiboldCompact: variable("type-heading-xl-semibold-compact"),
    textXlSemibold: variable("type-text-xl-semibold"),
    textLgMedium: variable("type-text-lg-medium"),
    textMdRegular: variable("type-text-md-regular"),
    textMdMedium: variable("type-text-md-medium"),
    textMdSemibold: variable("type-text-md-semibold"),
    textSmRegular: variable("type-text-sm-regular"),
    textSmMedium: variable("type-text-sm-medium"),
    symbolMdRegular: variable("type-symbol-md-regular"),
    lineHeightTextMd: variable("line-height-text-md"),
    trackingHeading: variable("tracking-heading"),
  },
  colors: Object.fromEntries(
    Object.keys(rawTheme.colors).map((key) => [
      key,
      variable(
        `color-${key.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)}`,
      ),
    ]),
  ) as { [Key in keyof typeof rawTheme.colors]: string },
  space: Object.fromEntries(
    Object.keys(rawTheme.space).map((key) => [key, variable(`space-${key}`)]),
  ) as { [Key in keyof typeof rawTheme.space]: string },
  radii: {
    xs: variable("radius-xs"),
    sm: variable("radius-sm"),
    md: variable("radius-md"),
    lg: variable("radius-lg"),
    xl: variable("radius-xl"),
  },
  shadows: {
    focus: variable("shadow-focus"),
    focusDanger: variable("shadow-focus-danger"),
    card: variable("shadow-card"),
  },
  sizes: {
    controlSm: variable("control-sm"),
    controlMd: variable("control-md"),
    controlLg: variable("control-lg"),
    controlXl: variable("control-xl"),
    controlHeight: variable("control-height"),
    tapTarget: variable("tap-target"),
    iconSm: variable("icon-sm"),
    iconMd: variable("icon-md"),
    iconLg: variable("icon-lg"),
  },
  layout: {
    pageMax: variable("page-max"),
    pageGutterDesktop: variable("page-gutter-desktop"),
    pagePaddingBlockDesktop: variable("page-padding-block-desktop"),
    contentMax: variable("content-max"),
    donationLayoutGap: variable("donation-layout-gap"),
    donationMediaWidth: variable("donation-media-width"),
    donationMediaInset: variable("donation-media-inset"),
    publicContentMax: variable("public-content-max"),
    publicImageMax: variable("public-image-max"),
    publicImageHeight: variable("public-image-height"),
  },
  motion: {
    instant: variable("motion-instant"),
    fast: variable("motion-fast"),
    base: variable("motion-base"),
    celebration: variable("motion-celebration"),
    easeStandard: variable("ease-standard"),
    easeEnter: variable("ease-enter"),
    easePlayful: variable("ease-playful"),
  },
} as const;
